version: "3.8"

services:
  ecommercenext:
    image: registry.gitlab.com/repository.host/nextjs-ecommerce:frontend-latest
    environment:
      - NEXT_PUBLIC_STRIPE_KEY=$NEXT_PUBLIC_STRIPE_KEY
      - NEXT_PUBLIC_PER_PAGE=$NEXT_PUBLIC_PER_PAGE
      - NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=cloud-public
        - traefik.http.routers.ecommercenext.entrypoints=websecure
        - traefik.http.routers.ecommercenext.rule=Host(`${FRONTEND_DOMAIN}`)
        - traefik.http.routers.ecommercenext.tls=true
        - traefik.http.routers.ecommercenext.tls.options=default
        - traefik.http.routers.ecommercenext.tls.certresolver=letsencrypt
        - traefik.http.routers.ecommercenext.middlewares=traefik-ratelimit,traefik-inflightreq
        - traefik.http.services.ecommercenext.loadbalancer.server.port=7777
    networks:
      - cloud-public

networks:
  cloud-public:
    external: true
